fix whitespace in copyfs-mount

diff --git a/copyfs-mount b/copyfs-mount
--- a/copyfs-mount
+++ b/copyfs-mount
@@ -25,16 +25,16 @@ fi
 # Check fuse module
 if ! grep fuse /proc/modules > /dev/null; then
     if [ $UID = 0 ]; then
-	modprobe fuse > /dev/null || {
-	    echo "Could not load fuse kernel module !" 1>&2
-	    exit 1
-	}
+        modprobe fuse > /dev/null || {
+            echo "Could not load fuse kernel module !" 1>&2
+            exit 1
+        }
     else
-	echo "You need the fuse kernel module to run this. As you are"
-	echo "not root, I can't load it. Become root and run :"
-	echo
-	echo "    modprobe fuse"
-	exit 1
+        echo "You need the fuse kernel module to run this. As you are"
+        echo "not root, I can't load it. Become root and run :"
+        echo
+        echo "    modprobe fuse"
+        exit 1
     fi
 fi
 
